### ISSUE TITLE
Error by testing GPT 3.5 engine

### ISSUE THREAD

**Issue by LukasCY** [bookfere/Ebook-Translator-Calibre-Plugin#131] opened 2023-09-19 21:54 UTC
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 66, in translate_text
  File "calibre_plugins.ebook_translator.engines.chatgpt", line 89, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 181, in get_result
Exception: Can not parse returned response. Raw data: 
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 171, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 429: Too Many Requests

**Comment by bookfere** [comment] 2023-09-20 04:21
Thank you for your feedback. However, the issue is indeed related to the rate limits of ChatGPT. If you are using the free version of ChatGPT, it's essential to ensure that the request frequency remains within the approved range, which is limited to 3 requests per minute. You can adjust the settings for the number of requests allowed within a specific time period in the plugin settings.

**Comment by LukasCY** [comment] 2023-09-20 08:30
I did not change the default setting... by the way, I am using gpt 4
[image: image.png]

书伴 ***@***.***> 於 2023年9月20日週三 上午6:21寫道：

**Comment by LukasCY** [comment] 2023-09-20 09:29
And it seems that the error message has changed:
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.components.engine", line 66, in translate_text
  File "calibre_plugins.ebook_translator.engines.chatgpt", line 89, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 181, in get_result
Exception: Can not parse returned response. Raw data: 
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 171, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 404: Not Found

**Comment by bookfere** [comment] 2023-09-20 09:43
Sorry, but we won't be able to assist you unless you provide enough information for us to analyze the issue you're facing. Please provide as much information as possible, such as the settings you've changed and whether you're using a network proxy. The more details you can provide, the better chance we have of resolving the problem.

**Comment by LukasCY** [comment] 2023-09-20 10:35
All the settings remain the same and I did not use any proxy.

书伴 ***@***.***> 於 2023年9月20日週三 上午11:43寫道：

**Comment by LukasCY** [comment] 2023-09-20 11:39
I mean they are still the default settings

**Closed** 2023-09-20 13:43 UTC
Labels: wontfix
