### ISSUE TITLE
Line break issue

### ISSUE THREAD

**Issue by YukinoshitaYukino123** [bookfere/Ebook-Translator-Calibre-Plugin#65] opened 2023-06-13 18:11 UTC
There is text file I want to translate, but after it the content got extracted suddenly a some {{id_number}} appear after punctuation
eg:
original
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/128869659/ef07134d-3956-49dc-afc2-3dfeb83eb8bc)
extracted
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/128869659/46139f28-d73b-4ae3-a5c8-f9f88e0a847e)

And also is there's a way to fix error 400:bad request, thanks

**Comment by bookfere** [comment] 2023-06-14 04:10
Did you enable the "Merge to Translate" feature in the plugin settings? If so, this is the expected behavior, as we need placeholders to identify the paragraphs you merged before translation.

What translation engine do you use when the "400:bad request" message occurs?

**Comment by YukinoshitaYukino123** [comment] 2023-06-14 09:38
Yes, I enable merge to translate since if I don't it will break break down my file into each sentence which make it slow. Then how do I remove the placeholder once the translation is finished?

I use google translate free

**Comment by bookfere** [comment] 2023-06-14 12:02
Once you enable the "**Merge to Translate**" feature, there's no need to worry about these placeholders as the plugin will handle them automatically. It's important not to remove these placeholders to ensure that the conversion works properly.

By the way, if you're using the "**Google (Free)**" translation engine, you can modify some settings to improve the translation speed. Navigate to "**Settings > General > HTTP Request**" and increase the value of "**Concurrency limit**" from the default `1` to a higher number, such as `100`. Additionally, decrease the "**Max interval**" from the default `5` to a smaller number, like `0`. These adjustments will help you achieve the desired speed.

**Comment by bookfere** [comment] 2023-06-15 10:01
It appears that the paragraph you wish to translate may have exceeded the limit for Google (Free). For this particular engine, it is recommended to keep the paragraph within 1800 CJK characters. Please confirm the character count of the paragraph that is encountering this error.

**Comment by YukinoshitaYukino123** [comment] 2023-06-15 19:56
Thanks, it works now but sometimes I encounter {{ID_number}} on the output (after finished translating the file and make and output) for example :
![image](https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/assets/128869659/98009bc2-3ab0-4b79-9625-2595bfa8b956)

**Comment by bookfere** [comment] 2023-06-16 09:48
Yes, this situation is common because the translation engine cannot guarantee that placeholders inserted into the original text will always be retained consistently in the translation.

**Comment by YukinoshitaYukino123** [comment] 2023-06-16 10:59
I see, also is there's a way around on merge to translate option for huge text file? Since I noticed that it skip alot of original text, but if I don't choose merge to translate, it is able to extract all the text albeit sentence by sentence.

**Comment by bookfere** [comment] 2023-06-16 11:42
The "Merge to Translate" feature always merges paragraphs depending on the character count you set in the settings, regardless of the size of the text file. Ideally, the paragraphs are not supposed to be ignored unless specific rules are specified in the "Ignore Paragraph" or "Ignore Elements" settings. Otherwise, it may be a bug.

**Comment by YukinoshitaYukino123** [comment] 2023-06-16 18:04
Apparently it's only happen to 1 of my file (for now), I've tried another files and they separate them well. Do I need to submit the file to be tested out?

**Comment by bookfere** [comment] 2023-06-18 11:31
Sure, you can send me the file via email address bookfere@gmail.com.

**Comment by bookfere** [comment] 2023-06-18 11:56
OK, I received the email you sent. The sample text you provided may help the plugin fix the error you encountered. This issue has been closed, but feel free to open a new one if you encounter any further problems in the future.

**Closed by bookfere** 2023-06-18 11:56 UTC
Labels: enhancement
